### ISSUE TITLE
Stuck on "Booting Conductor" screen (Mac OSX High Sierra)

### ISSUE THREAD

**Issue by lorenjohnson** [holochain/holoscape#3]
On initial and any subsequent runs I can't get past the splash screen with "Booting Conductor". 

Including full Conductor Log.

![image](https://user-images.githubusercontent.com/6294/63599746-0f4d1200-c577-11e9-8046-154dc74a8317.png)
![image](https://user-images.githubusercontent.com/6294/63599765-1b38d400-c577-11e9-8558-05a30f86644c.png)
[conductor-log.txt](https://github.com/holochain/holoscape/files/3534931/conductor-log.txt)

**Comment by lorenjohnson** [comment]
Same issue/error on @robbiecarlton's machine on Mojave 10.14

**Comment by Connoropolous** [comment]
I saw these issues in unrelated work I was doing today as well, using
Holochain...

It has to do with trying to download and install n3h, which it is supposed
to do automatically.

A possible fix is to have n3h version 0.0.20 available on your path.

Download Holochain/n3h to your system, run `npm install` in that folder,
then add `export $PATH=/path/to/n3h/bin:$PATH` to your shell profile

**Comment by lucksus** [comment]
Yeah, that can also happen if the conductor could not start, which most likely is because there is an old conductor process running which listens on the same ports. What I wanted to add but didn’t get to is showing the log if we couldn’t connect within 30 secs..

**Comment by lucksus** [comment]
I just pushed two commits to master:
* The splash screen now shows the conductor log output in the background
* If the start-up is not complete after 60 seconds, it will show a message box and open the proper log window.

@lorenjohnson, can you try again (just running `npm run` from the repo root) and post your log messages?

**Comment by lucksus** [comment]
There are many fixes and improvements since August. I will close this issue assuming it got resolved. Please re-open should I be mistaken.

**Comment by pdaoust** [comment]
On Holoscape 0.0.3, I get the log window (it's blank though --- just an indigo gradient). However, the splash screen sticks around even after the log window closes, and it's one of those always-on-top windows so it makes it hard to get back to the term to shut the thing down (thank goodness for virtual desktops!)
