### ISSUE TITLE
When using Mac, closing Holoscape leads to 5 crazy JS errors throwing alerts

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holoscape#30]
They all pretty look like this, and appear one at a time.

<img width="420" alt="Screen Shot 2019-10-30 at 5 00 19 PM" src="https://user-images.githubusercontent.com/1409121/67898623-06f4f280-fb37-11e9-82bc-6d9dce7c1d89.png">

**Comment by lucksus** [comment]
Does this happen when closing via the system tray pop-up menu, or via the macOS title menu?

**Comment by Connoropolous** [comment]
The app bar.
