### ISSUE TITLE
Install a DHT with no UI

### ISSUE THREAD

**Issue by philipbeadle** [holochain/holoscape#62]
How do I write a bundle file to just install a DHT. 
```
bridges = []

[[instances]]
name = "notes"
id = "__notes"
dna_hash = "QmQRKZdTk6NSW5eg8UaSwcJCKgu9pHEcHhezM5yc9vtcZa"
uri = "file:./dna/dist/dna.dna.json"
```

The install button never enables.

**Comment by lucksus** [comment]
You will have to declare the UIs array as empty, similar to bridges  in the first line. So add a line with:
UIs=[]

**Comment by philipbeadle** [comment]
Thanx Nico.
